### ISSUE TITLE
Show disabled autoresponders as well.

### ISSUE THREAD

**Issue by ram4nd** [sendsmaily/smaily-magento-extension#11]
https://github.com/sendsmaily/smaily-magento-extension/blob/40417b279ea8b740c2217f1065e28aef2f9d2496/Helper/Data.php#L160

**Comment by sinukaarel** [comment]
Fixed with 
https://github.com/sendsmaily/smaily-magento-extension/commit/50f233594b2c37a7224f6a868779467a12f175d3
