### ISSUE TITLE
Newsletter subscribers synchronization inefficient

### ISSUE THREAD

**Issue by kaittodesk** [sendsmaily/smaily-magento-extension#36]
Newsletter subscribers synchronization can be inefficient (and crash) when synchronizing a lot of subscribers for the first time, because all of the subscribers are loaded from database into memory.

Subscribers synchronization must be reworked to fetch subscribers from database and synchronize to Smaily in batches.

**Comment by TomAbel** [comment]
Subscribers are retrieved from database via `fetchAll()`, which can be memory inefficient for large data sets. Some websites might be disabled or have customer synchronization disabled, in that case using `fetchAll()` might query a lot of unnecessary subscribers. Maybe subscribers could be queried by website ID

**Comment by kaittodesk** [comment]
Fixed by #61
