### ISSUE TITLE
Built-in CAPTCHA creates double input boxes

### ISSUE THREAD

**Issue by marispulk** [sendsmaily/smaily-magento-extension#46]
**Bug description**
Magento Built-In CAPTCHA creates double CAPTCHA input boxes.

**Steps for reproducing**

1. Go to magento2.smaily.dev admin panel.
2. Click on Stores -> Configuration -> Smaily Email Marketing And Automation -> Module Configuration.
3. Scroll down to CAPTCHA Type -> Switch to Magento Built-In CAPTCHA -> Save Config.
4. Flush Magento Cache from Cache Management (message appears at the top of the page).
5. Go to magento2.smaily.dev.
6. Insert email and CAPTCHA -> Subscribe.
7. Now extra input box for CAPTCHA is displayed.

**Expected behavior**
Displays only success or error message.

**Actual behavior**
Extra input box appears at the bottom of the page, after pressing the subscribe button.

**Screenshots**
![Home page](https://i.imgur.com/tEuZjia.png)

**Magento version**
Version 2.3.6

**Module version**
Version 1.0.2

**Comment by kaittodesk** [comment]
Fixed with #61
