### ISSUE TITLE
Use makefile in place of Tusk

### ISSUE THREAD

**Issue by TomAbel** [sendsmaily/smaily-magento-extension#47]
Tusk is great for providing instructions on how the build the project and also includes some handy commands, like installing sample data.
Specifying a makefile would basically do the same job as tusk and doesn't need to be separately installed as it's a GNU package. Starting containers could be handled by `make up`

**Comment by kaittodesk** [comment]
An alternative would be to drop the need for running a separate command to install Magento and sample data all together. I have (a working) solution in https://github.com/sendsmaily/smaily-magento-extension/compare/ops/development-environment branch, that utilizes Docker Compose for setting up and running the development environment without the need of executing commands manually.

**Comment by kaittodesk** [comment]
Resolved by #54.

Tusk is no longer required, and everything runs off of Docker Compose.
